### ISSUE TITLE
feature request - support other languages, support internationalization

### ISSUE THREAD

**Issue by JustFly1984** [fymmot/inclusive-dates#17]
Currently it works only with english language.

**Comment by fymmot** [comment]
@JustFly1984 
Yesterday I released a rewrite of the component that does have support for more languages.

It uses native `Intl.DateTimeFormat `so you should just need to provide a BCP-47 language code, and a list of your own translations for the buttons and labels. 

Be aware that natural language parsing is only available in some locales. Have a look at Chronos section on supported locales: https://github.com/wanasit/chrono#locales . If your locale is not on the list, the input will be limited to ISO-formatted dates (YYYY-MM-DD)

It's a very early version though so probably a lot of things will be broken. But please have a look and tell me what you think!

https://fymmot.github.io/inclusive-dates/
