### ISSUE TITLE
"previous/last 12 december"

### ISSUE THREAD

**Issue by rudiedirkx** [fymmot/inclusive-dates#18]
Turns into 12 dec 2020 instead of 2019.

**Comment by useit-consulting** [comment]
Thanks for reporting!
This looks like an issue with the language parser (https://github.com/wanasit/chrono), it doesn't handle "previous/last" correctly out of the box. But we're not using the latest version of Chrone, perhaps this has been improved in later versions. 

Feel free to look into the issue!
