### ISSUE TITLE
"day before yesterday"

### ISSUE THREAD

**Issue by Poopooracoocoo** [fymmot/inclusive-dates#20]
returns same result as "yesterday"

**Comment by fymmot** [comment]
@Poopooracoocoo 
Yes Chrono.js (the date parser used) is very aggressive when it finds "yesterday" or "tomorrow". 

Perhaps it would be possible to use the options in Chrono for refining the results (https://github.com/wanasit/chrono#customize-chrono) but I have not had a chance to try it yet.
