### ISSUE TITLE
How to use on a basic site without NPM?

### ISSUE THREAD

**Issue by dmikester1** [fymmot/inclusive-dates#21]
How do we use this library on a basic site with no NPM and with just a script tag to include it?

**Comment by fymmot** [comment]
Hi @dmikester1 
It's been a while but I just released a completely rewritten version of the component. It's available as import from NPM with a bundler, or using a script tag. There are instructions here: https://fymmot.github.io/inclusive-dates/#usage

Let me know if you have any questions!
